# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.wmean <- function(x, w) {
    .Call('edarf_wmean', PACKAGE = 'edarf', x, w)
}

vestl <- function(n, ntree, pd_membership, yvar, inbag) {
    .Call('edarf_vestl', PACKAGE = 'edarf', n, ntree, pd_membership, yvar, inbag)
}

